# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - persist_to_workspace:
          root: .
          paths:
            - .

  sonarqube:
    working_directory: ~/build
    docker:
      - image: sonarsource/sonar-scanner-cli  # Using sonar-scanner-cli image with sonar-scanner pre-installed
    resource_class: small
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - run:
          name: "Run SonarQube Scanner"
          command: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            sonar-scanner \
              -Dsonar.projectKey="${SONAR_PROJECT_KEY}" \
              -Dsonar.organization="${SONAR_ORG}" \
              -Dsonar.host.url="https://sonarcloud.io" \
              -Dsonar.login="${SONAR_TOKEN}"

workflows:
  main-workflow:
    jobs:
      - say-hello
      - sonarqube:
          requires:
            - say-hello
