name: DevSecOps Security Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  static_analysis:
    name: Static Analysis and Security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant Execute Permissions
        run: chmod +x ./gradlew

      - name: Run Lint (Security Analysis)
        run: ./gradlew lint

      - name: Run Dependency Check
        run: ./gradlew dependencyCheckAnalyze

  test_pull_request:
    name: Test Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant Execute Permissions
        run: chmod +x ./gradlew

      - name: Run Unit Tests
        run: ./gradlew test
