name: Main Development Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 31
          target: android-31
          build-tools: 31.0.0

      # Step 4: Cache Gradle Files
      - name: Cache Gradle Files
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      # Step 5: Grant Execute Permissions for gradlew
      - name: Grant Execute Permissions
        run: chmod +x ./gradlew

      # Step 6: Build and Test Application
      - name: Build and Test Application
        run: ./gradlew clean build test --stacktrace

      # Step 7: Upload Test Results
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: app/build/reports/tests/testDebugUnitTest

  integration_tests:
    name: Integration Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Grant Execute Permissions for gradlew
      - name: Grant Execute Permissions
        run: chmod +x ./gradlew

      # Step 4: Run Integration Tests
      - name: Run Integration Tests
        run: ./gradlew connectedDebugAndroidTest --stacktrace
