name: Main Development Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Application
        run: ./gradlew assembleDebug

      - name: Run Unit Tests
        run: ./gradlew test
