name: Main Development Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Grant Execute Permissions for gradlew
      - name: Grant Execute Permissions
        run: chmod +x ./gradlew

      # Step 4: Build the Application
      - name: Build Application
        run: ./gradlew assembleDebug

      # Step 5: Run Unit Tests
      - name: Run Unit Tests
        run: ./gradlew test
